main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "main"

urlpatterns = [
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path("register", views.register, name="register"),
    path("homepage", views.homepage, name="homepage"),
    path("orphanage/<int:id>", views.orphanage_details, name="orphanage_details"),
    path("orphanage_registration", views.register_orphanage, name="orphanage_registration"),
    path("admit_orphan", views.admit_orphan, name="admit_orphan"),
    path("orphanages", views.orphanages, name="orphanages"),
    path("events", views.events, name="events"),
    path("adoption", views.adoption, name="adoption"),
    path("about_us", views.about_us, name="about_us"),
]

# orphanage_registration.html

websiteProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls'),name="main"),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime

states_choices = (
		("1","Andhra Pradesh"),
		("2 ","Arunachal Pradesh "),
		("3","Assam"),
		("Bihar","Bihar"),
		("Chhattisgarh","Chhattisgarh"),
		("Goa","Goa"),
		("Gujarat","Gujarat"),
		("Haryana","Haryana"),
		("Himachal Pradesh","Himachal Pradesh"),
		("Jammu and Kashmir","Jammu and Kashmir"),
		("Jharkhand","Jharkhand"),
		("Karnataka","Karnataka"),
		("Kerala","Kerala"),
		("Madhya Pradesh","Madhya Pradesh"),
		("Maharashtra","Maharashtra"),
		("Manipur","Manipur"),
		("Meghalaya","Meghalaya"),
		("Mizoram","Mizoram"),
		("Nagaland","Nagaland"),
		("Odisha","Odisha"),
		("Punjab","Punjab"),
		("Rajasthan","Rajasthan"),
		("Sikkim","Sikkim"),
		("Tamil Nadu","Tamil Nadu"),
		("Telangana","Telangana"),
		("Tripura","Tripura"),
		("Uttar Pradesh","Uttar Pradesh"),
		("Uttarakhand","Uttarakhand"),
		("West Bengal","West Bengal"),
		("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),
		("Chandigarh","Chandigarh"),
		("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),
		("Daman and Diu","Daman and Diu"),
		("Lakshadweep","Lakshadweep"),
		("National Capital Territory of Delhi","National Capital Territory of Delhi"),
		("Puducherry","Puducherry")
	)


# Create your models here.
class Orphanage(models.Model):
	orphanage_name = models.CharField(max_length=200)
	image = models.ImageField(upload_to="orphanage/images/")
	establish_date = models.DateField(default=datetime.date(datetime.now()))
	about = models.TextField()
	address = models.TextField()
	state = models.CharField(max_length=35, choices=states_choices)
	contact_no = models.CharField(max_length=15)
	site_url = models.CharField(max_length=200)
	email = models.EmailField(max_length=150)
	children_count = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.orphanage_name

class Orphan(models.Model):
	gender_choices = [("M", "Male"), ("F", "Female"), ("O", "Other")]
	orphan_name = models.CharField(max_length=200)
	orphan_image = models.ImageField(upload_to="orphan/images/")
	age = models.PositiveIntegerField()
	gender = models.CharField(max_length=10, choices=gender_choices)
	admit_to = models.ForeignKey(Orphanage, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.orphan_name


class Event(models.Model):
	event_name = models.CharField(max_length=500)
	event_type = models.CharField(max_length=300)
	poster = models.ImageField(default="", upload_to="events/images")
	description = models.TextField()
	event_date = models.DateField(default=datetime.date(datetime.now()))
	event_time = models.TimeField(default=datetime.time(datetime.now()))
	organised_by = models.ForeignKey(Orphanage, on_delete = models.CASCADE)
	venue = models.TextField()

	def __str__(self):
		return self.event_name


class Feedback(models.Model):
	title = models.CharField(max_length=100)
	name = models.CharField(max_length=200)
	review = models.TextField()
	email = models.EmailField()
	mobile_no = models.CharField(max_length=15)
	feedback_for = models.ForeignKey(Orphanage, on_delete=models.CASCADE)

	def  __str__(self):
		return self.title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Orphanage, states_choices, Orphan, Feedback


class SignUpForm(UserCreationForm):
    username    = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    first_name  = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}), max_length=32)
    last_name   = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}), max_length=32)
    email       = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}), max_length=64)
    password1   = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2   = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email',)


class OrphanageForm(forms.ModelForm):
    class Meta:
        model = Orphanage   
        fields = '__all__'
        

class OrphanForm(forms.ModelForm):
    class Meta:
        model = Orphan
        fields = "__all__"

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import *
from . import forms
from django.contrib import messages
# Create your views here.

def homepage(request):
	if request.method == 'POST':
		form = forms.FeedbackForm(request.POST)
		if form.is_valid():
			print(form.cleaned_data)
			orphanage = form.save()
			messages.success(request, f"Feedback Submitted Successfully!!!")
		else:
			messages.error(request, "Something Went Wrong")

	form = forms.FeedbackForm
	events = Event.objects.all()
	context = {'events':events[0:3], 'form':form}
	return render(request=request, template_name = "main/home.html", context = context)


def logout_request(request):
	logout(request)
	messages.info(request, "You are logged out.")
	return redirect("main:homepage")

def login_request(request):
	next_page = None
	
	if request.method == 'GET':
		next_page = request.GET.get('next')
	if next_page != None:
		messages.error(request, "Need to login first")		

	print("Next PAGE IS :: ")
	print(next_page)

	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			uname = form.cleaned_data.get('username')
			pwd = form.cleaned_data.get('password')
			user = authenticate(username=uname, password=pwd)
			if user is not None:
				login(request, user)
				messages.info(request, "Successfully logged In")
				
				if next_page == None:
					return redirect("main:homepage")					
				else:
					return redirect("main:"+next_page[1:])
			else: 
				messages.error(request, "Credentails are not Valid.")
		else: 
				messages.error(request, "Something went wrong")
	
	form = AuthenticationForm
	context = {"form":form}
	return render(request, "main/login.html", context)


def register(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		pwd = request.POST.get('password1')
		pwd2 = request.POST.get('password2')
		if pwd != pwd2:
			messages.error(request, "Passwords do not match")

		if form.is_valid():
			fname = request.POST.get('first_name')
			lname = request.POST.get('last_name')
			uname = request.POST.get('username')
			email = request.POST.get('email')
			

			if pwd != pwd2:
				messages.error(request, "Passwords do not match")
				# return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
			else:
				user = User.objects.create_user(uname, email, pwd)
				user.first_name = fname
				user.last_name = lname
				user.save()

				messages.success(request,"User Register Successfully")

				login(request, user)
				messages.info(request, f"You are logged in as {uname}")
				return redirect("main:homepage")

		else:
			for msg in form.error_messages:
				messages.error(request, f"{form.error_messages[msg]}")


	form = forms.SignUpForm
	context = {"form":form}
	return render(request=request, 	
				  template_name="main/register.html", 
				  context = context)


@login_required(login_url="/login")
def about_us(request):
	return render(request, 'main/aboutUs.html')

@login_required(login_url="/login")
def orphanages(request):
	orphanages = Orphanage.objects.all()
	context = {'orphanages': orphanages}
	return render(request, "main/orphanages.html", context)

@login_required(login_url="/login")
def events(request):
	events = Event.objects.all()
	context = {'events':events}
	return render(request, "main/events.html",context)


def orphanage_details(request, id):
	orpng = Orphanage.objects.get(id=id)
	feedbacks = Feedback.objects.filter(feedback_for=orpng)
	events = Event.objects.filter(organised_by=orpng)
	children = Orphan.objects.filter(admit_to = orpng)
	context = {"orp":orpng, "events":events, 'children':children,'feedbacks':feedbacks}
	print(orpng)
	return render(request, "main/orpng_details.html", context)


def register_orphanage(request):
	if request.method == 'POST':
		form = forms.OrphanageForm(request.POST, request.FILES)
		if form.is_valid():
			print(form.cleaned_data)
			orphanage = form.save()
			messages.success(request, f"Orphanage Register Successfully")
			return redirect("main:orphanages")
		else:
			messages.error(request, "Something Went Wrong")

	form = forms.OrphanageForm
	context = {'form':form}
	return render(request, "main/orphanage_registration.html",context)

def admit_orphan(request):
	if request.method == 'POST':
		form = forms.OrphanForm(request.POST, request.FILES)
		if form.is_valid():
			print(form.cleaned_data)
			orphanage = form.save()
			messages.success(request, f"Admission Request Sent please bring the child to the {form.cleaned_data.get('admit_to')}")
			return redirect("main:homepage")
		else:
			messages.error(request, "Something Went Wrong")

	form = forms.OrphanForm
	context = {'form':form}
	return render(request, "main/admit_orphan.html",context)

def adoption(request):
	return render(request, 'main/adoption.html')

main/templates/main/aboutUs.html
{%extends "main/base.html" %}
{% load static %}
{% block ccss %}
	<style type="text/css">
		@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&display=swap');

*{
    box-sizing: border-box;
    padding: 0;
    margin: 0;
}
body{
    display: grid;
    align-content: center;
    min-height: 100vh;
}
section{
    display: grid;
    grid-template-columns: 1fr 1fr;
    min-height: 70vh;
    width: 75vw;
    /*margin: 0 auto;*/
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border-radius: 12px
}
.image{
    background-color: #12192c;
    display: flex;
    border-radius: 12px 0 0 12px;
}
.image img{
height:50vh;
margin:50px auto
}
.content{
    background-color: #12192c;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
    border-radius: 0  12px 12px 0;
    color: #fff;
}
.content h2{
    text-transform: uppercase;
    font-size: 36px;
    letter-spacing: 6px;
    opacity: 0.9;
}
.content span{
    height: 0.5px;
    width: 80px;
    background: #777;
    margin: 30px 0;
}
.content p{
    padding-bottom: 15px;
    font-weight: 300;
    opacity: 0.7;
    width: 60%;
    text-align: center;
    margin: 0 auto;
    line-height: 1.7;
    color:#ffffff
}
.links{
    margin: 15px 0;
}
.links li{
    border: 2px solid #4158D0;
    list-style: none;
    border-radius: 5px;
    padding: 10px 15px;
    width: 160px;
    text-align: center;
}
.links li a{
    text-transform: uppercase;
    color: #fff;
    text-decoration: none;
}
.links li:hover{
    border-color: #C850C0;
}

.vertical-line{
    height: 30px;
    width: 3px;
    background: #C850C0;
    margin: 0 auto;
}
.icons{
    display: flex;
    padding: 15px 0;
}
.icons li{
    display: block;
    padding: 5px;
    margin: 5px;
}
.icons li i{
    font-size: 26px;
    opacity: 0.8;
}
.icons li i:hover{
    color: #C850C0;
    cursor: pointer;
}


/*******/

@media(max-width: 900px){
    section{
        grid-template-columns: 1fr;
        width: 100%;
        border-radius: none;
    }
    .image{
        height: 100vh;
        border-radius: none;
    }
    .content{
        height: 100vh;
        border-radius: none;
    }
    .content h2{
        font-size: 20px;
        margin-top: 50px;
    }
    .content span{
        margin: 20px 0;
    }
    .content p{
        font-size: 14px;
    }
    .links li a{
        font-size: 14px;
    }
    .links{
        margin: 5px 0;
    }
    .links li{
        padding: 6px 10px;
    }
    .icons li i{
        font-size: 15px;
    }
}
.credit{
    text-align: center;
    color: #000;
    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
  }
  
  .credit a{
    text-decoration: none;
    color:#000;
    font-weight: bold;
  }
</style>

{% endblock %}

{% block base %}
    <div id="modal1" class="modal">
    <div class="modal-content">
      <div class="center-align"><h5>User Details</h5></div>
      <p><strong>Username : </strong>{{user.username}}</p>
      <p><strong>First Name : </strong>{{user.first_name}} | <strong>Last Name : </strong>{{user.last_name}}</p>
      <p><strong>Email Address : </strong>{{user.email}}</p>
    </div>
  </div>

	<nav class="purple">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo"> &nbsp; OrphanCare</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger">
            <i class="large material-icons">menu</i>
          </a>
          <ul class="right hide-on-med-and-down">
            <li><a style="font-size:130%" href="/homepage">Home</a></li>
            <li><a style="font-size:130%"  href="/orphanages">Orphanages</a></li>
            <li><a style="font-size:130%"  href="{% url 'main:adoption' %}">Adoption</a></li>
            <li><a style="font-size:130%"  href="/events">Events</a></li>
            <li><a style="font-size:130%"  href="/about_us">About Us</a></li>
            {% if user.is_authenticated %}
                 <li>
                    <a style="font-size:130%" data-target="modal1" class=" pink darken-3 modal-trigger">{{user.username|title}}</a>
                 </li>

                 <li>
                        <a class="pink darken-4" style="font-size:130%" href="/logout">Logout</a>
                    </li>
            {% else %}
                <li><a style="font-size:130%" href="/register">Register</a></li>
                <li><a style="font-size:130%"  href="/login">Login</a></li>             
            {% endif %}
          </ul>
        </div>
    </nav>

	<ul class="sidenav purple lighten-3" id="mobile-demo">
		<br>
		
		<li  class="brand-logo"><a style="font-size:170%" href="#!" class=" pink-text text-darken-3 brand-logo"> OrphanCare</a></li>
		<br>
		<li><a style="font-size:130%" href="/homepage">Home</a></li>
		<li><a style="font-size:130%"  href="/orphanages">Orphanages</a></li>
    	<li><a style="font-size:130%"  href="/events">Events</a></li>
    	<li><a style="font-size:130%"  href="/about_us">About Us</a></li>
		{% if user.is_authenticated %}
			<li><a class="pink darken-3" style="font-size:150%"  href="/account">{{user.username|title}}</a></li>
			<li><a class="pink darken-4" style="font-size:150%" href="/logout">Logout</a></li>
		{% else %}
			<li><a style="font-size:130%" href="/register">Register</a></li>
			<li><a style="font-size:130%"  href="/login">Login</a></li>
		{% endif %}
	</ul>


	<div class="container">
			<section class="row">
        <div class = "image">
           <img src="{% static 'placeholders/mom_son.png' %}">
        </div>

        <div class = "content">
            <h2>About Us</h2>
            <p>OrphanCare Foundation advocates and works to give children in institutions and unplanned newborn babies the opportunity to grow in the care of a family. We believe no child should be abandoned or denied the love and care of a family.</p>
            <ul class = "links">
                <li><a href = "#">work</a></li>
                <div class = "vertical-line"></div>
                <li><a href = "#">service</a></li>
                <div class = "vertical-line"></div>
                <li><a href = "#">contact</a></li>
            </ul>
            <ul class = "icons">
                <li>
                    <i class = "fa fa-twitter"></i>
                </li>
                <li>
                    <i class = "fa fa-facebook"></i>
                </li>
                <li>
                    <i class = "fa fa-github"></i>
                </li>
                <li>
                    <i class = "fa fa-pinterest"></i>
                </li>
            </ul>
        </div>
    </section>
    <br>
        <div class="credit">Made with <span style="color:tomato">❤</span> and Care.</div>
	</div>
{% endblock %}

main/templates/main/admit_orphan.html
{%extends "main/header.html" %}

{% block content %}
	
	<br>
	<div>
    	<h4 style="font-weight: bold; font-size: 250%" class="flow-text teal-text text-lighten-2 center-align">Orphan Registration</h4>
  	</div>
  	<br>
	<form method="POST" class="input-field" enctype="multipart/form-data">
		{%csrf_token%}
		{{form.as_p}}

		<button class="btn", type="submit">
			Admit 
		</button>
	</form>
	<br>
	<br><br>
	<br>
	
{% endblock %}	

main/templates/main/header.html
{% extends "main/base.html" %}

{% block base %}
	<div id="modal1" class="modal">
    <div class="modal-content">
      <div class="center-align"><h5>User Details</h5></div>
      <p><strong>Username : </strong>{{user.username}}</p>
      <p><strong>First Name : </strong>{{user.first_name}} | <strong>Last Name : </strong>{{user.last_name}}</p>
      <p><strong>Email Address : </strong>{{user.email}}</p>
    </div>
  </div>

	<nav class="purple">
	    <div class="nav-wrapper">
	      <a href="#!" class="brand-logo"> &nbsp; OrphanCare</a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger">
	      	<i class="large material-icons">menu</i>
	      </a>
	      <ul class="right hide-on-med-and-down">
	        <li><a style="font-size:130%" href="/homepage">Home</a></li>
        	<li><a style="font-size:130%"  href="/orphanages">Orphanages</a></li>
        	<li><a style="font-size:130%"  href="{% url 'main:adoption' %}">Adoption</a></li>
        	<li><a style="font-size:130%"  href="/events">Events</a></li>
        	<li><a style="font-size:130%"  href="/about_us">About Us</a></li>
	        {% if user.is_authenticated %}
	             <li>
	             	<a style="font-size:130%" data-target="modal1" class=" pink darken-3 modal-trigger">{{user.username|title}}</a>
	             </li>

	             <li>
	             		<a class="pink darken-4" style="font-size:130%" href="/logout">Logout</a>
	             	</li>
	        {% else %}
	        	<li><a style="font-size:130%" href="/register">Register</a></li>
	            <li><a style="font-size:130%"  href="/login">Login</a></li>	            
	        {% endif %}
	      </ul>
	    </div>
  	</nav>

	<ul class="sidenav purple lighten-3" id="mobile-demo">
		<br>
		
		<li  class="brand-logo"><a style="font-size:170%" href="#!" class=" pink-text text-darken-3 brand-logo"> OrphanCare</a></li>
		<br>
		<li><a style="font-size:130%" href="/homepage">Home</a></li>
		<li><a style="font-size:130%"  href="/orphanages">Orphanages</a></li>
    	<li><a style="font-size:130%"  href="/events">Events</a></li>
    	<li><a style="font-size:130%"  href="{% url 'main:adoption' %}">Adoption</a></li>
    	<li><a style="font-size:130%"  href="/about_us">About Us</a></li>
		{% if user.is_authenticated %}
			<li><a class="pink darken-3 modal-trigger" data-target="modal1" style="font-size:150%"  href="#">{{user.username|title}}</a></li>
			<li><a class="pink darken-4" style="font-size:150%" href="/logout">Logout</a></li>
		{% else %}
			<li><a style="font-size:130%" href="/register">Register</a></li>
			<li><a style="font-size:130%"  href="/login">Login</a></li>
		{% endif %}
	</ul>


  	{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:2000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:3000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}

        
    <div class="container">
    	{% block content %}
	    {% endblock %}
    </div>

    <footer class="page-footer purple">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">OrphanCare</h5>
          <p class="grey-text text-lighten-4"><strong>A Helping hand to the unpreviledged children. </strong> Not all of us can do great things but we can do small things with great love.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Some Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">FAQs</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Privacy Policy</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Terms of Service</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright purple darken-3">
      <div class="container">
      © 2020 Copyright OrphanCare. All Rights Reserved.
      <a class="grey-text text-lighten-4 right" href="#!">Support Us</a>
      </div>
    </div>
  </footer>
{% endblock %}

main/templates/main/home.html
{%extends "main/header.html" %}
{% load static %}

{% block content %}
	<h5><p class="flow-text">OUR VISION</p></h5>
	<blockquote>
          <h6>
            All children without supportive family structures in India should have their basic needs met and have access to quality education, security and health care.
          </h6>
    </blockquote>

    <h5>
        <p class="flow-text">OUR MISSION</p>
    </h5>
        <blockquote>
            <h6>
            Mission: Ensure every needy child is reached and has access to all their basic needs, including but not limited to, education, health, shelter, food and clothing.
            </h6>
        </blockquote>
    <hr>

   <h5 class="red-text center-align text-darken-1">Found an Orphan? Please sent them to an Orphanage.</h5>
    
    <nav class="teal lighten-2">
        <a href="{% url 'main:admit_orphan' %}" class="breadcrumb">
            <div class="col s12 center-align">
                Online Orphan Registration
            </div>
        </a>
    </nav>
    <br>
    <hr>
    
    <h4 class="left-align purple-text">Events @ various Orphanages :</h4>
    
    <br>

    <div class="row">
    {% for eve in events %}
        <div class="col s12 m6 l4">
            <div class="card z-depth-5">
                <div class="card-image">
                    <img src="{{eve.poster.url}}">
                </div>
                <div class="card-content">
                    <span class="card-title activator purple-text text-darken-4">{{eve.event_name}}
                        <i class="purple-text material-icons right">arrow_upward</i>
                    </span>
                    <p><strong>Organized By :</strong> {{eve.organised_by.orphanage_name}}</p>
                    <p><strong>Date :</strong> {{eve.event_date}}</p>
                    <p><strong>Timing :</strong> {{eve.event_time}}</p>
                    <p><strong>Venue :</strong> {{eve.venue}}</p>
                </div>
                <div class="card-reveal">
                     <span class="card-title grey-text text-darken-4"><strong>{{eve.event_name}}</strong><i class="material-icons right">close</i></span>
                    <p>{{eve.description}}</p>
                </div>
            </div>
        </div>  
    {% endfor %}
    </div>

    <br>
        <a href='/events' class="waves-effect waves-light btn-large">View More Events</a>
    <br>    

    
    
    <div>
        <h4 style="font-weight: bold; font-size: 250%" class="flow-text teal-text text-lighten-2 center-align">
            Feedback/Comments
        </h4>
    </div>

    <p class="flow-text red-text text-darken-2">
        Attended any event organized by the related orphanages or ever visited any of our related Orphanage, 
    then please leave a feedback or comment for training and improvement purpose. <strong>Thank You</strong></p>

    <form method="POST" class="input-field" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <button class="btn", type="submit">
            Review
        </button>
    </form>
    <br>
    <br>
{% endblock %}

main/templates/main/login.html
{%extends "main/header.html" %}

{% block content %}
	
	<br>
	<div>
    	<h4 style="font-weight: bold; font-size: 250%;" class="flow-text teal-text text-lighten-2 center-align">Login</h4>
  	</div>
  	<br>

	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		
		
		<button class="btn", type="submit">
	 		Login
	 	</button>
	</form>
 
	If you do not have a account <a href="/register"><strong>Register</strong></a> instead.

<br>
<br>	
{% endblock %}

main/templates/main/orphanages.html
{%extends "main/header.html" %}

{% block content %}
	<p style="font-weight: bold; font-size: 150%" class="flow-text teal-text text-lighten-2 center-align">
		Here are some of the many Orphanages all over the country. These all orphanages are genuine 
		and are verified by the <strong>goverment of India</strong>. 
		Any indian married couple can legally adopt a child from these orphanages and if someone finds an orphan, they can submit them to these orphanages as well.
	</p>

	<h5><strong>Orphanages</strong></h5>

	<div class="row">
		{% for orp in orphanages %}		
			<div class="col s12">
				<div class="card indigo lighten-2">
					<div class="card-content white-text">
					  <span class="card-title">
						<div class="row">	
							<div class="grid-example col s12 m7">
								<span class="flow-text"><strong>{{forloop.counter}}. {{orp.orphanage_name}}</strong> </span>
							</div>
							<div class="grid-example col s12 m5">
								<div class="right-align">
									<span class="flow-text">{{orp.state}}</span>
								</div>
							</div>
						</div>
					  </span>
					  <p>{{orp.about}}</p>
					</div>
					<div class="card-action">
					  <a class="valign-wrapper" href="{% url 'main:orphanage_details' id=orp.id %}"> View More &nbsp;
					  	<i class="tiny material-icons">call_made</i>
					  </a>				  
					  <a class="valign-wrapper" href="#">
					  	<i class="material-icons">call</i>{{orp.contact_no}}
					  </a>
					</div>
				</div>
			</div>

		{% endfor %}
	</div>

	<a href="{% url 'main:orphanage_registration' %}" class="waves-effect waves-light btn-large">Register Orphanage</a>
	<br>
	<br>
{% endblock %}